CREATE TABLESPACE wahwahdev
DATAFILE '/opt/oracle/oradata/wahwahdev.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
DEFAULT STORAGE(INITIAL 128K NEXT 64K PCTINCREASE 10);

ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER wahwahmaster IDENTIFIED BY "1234"
DEFAULT TABLESPACE wahwahdev 
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, DBA TO wahwahmaster;
