version: '3.8'

services:
  apache2:
    build:
      context: ./Apache
      dockerfile: Dockerfile
    container_name: apache2
    ports:
      - "80:80"
    networks:
      - app-network

  oracledb:
    platform: linux/amd64
    build:
      context: ./Oracle
      dockerfile: Dockerfile
    container_name: oracledb
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - oracledb
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
