version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  oracledb:
    image: jinkyoungheo/oracle-xe:11g
    container_name: oracledb
    environment:
      ORACLE_PASSWORD: 1234
      ORACLE_ALLOW_REMOTE: true
    ports:
      - "1521:1521"
    networks:
      app-network:
        ipv4_address: 192.168.100.100

  backend:
    #image: kokomong2docker/my-backend:latest
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - oracledb

    ports:
      - "8080:8080"
    networks:
      - app-network
