CREATE TABLESPACE team4DB
DATAFILE '/opt/oracle/oradata/wahwahdev.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
DEFAULT STORAGE(INITIAL 128K NEXT 64K PCTINCREASE 10);

ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER team4master IDENTIFIED BY "1234"
DEFAULT TABLESPACE team4DB
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, DBA TO team4master;
